spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://ec2-18-209-78-11.compute-1.amazonaws.com:5432/d81i6vai6dip58
    password: 38af0dd7400cbcc0f30dc6bcba473df30b643ceb558cfadfb72ca69a2e2a98a1
    username: beqrvklfuhntgd
    driver-class-name: org.postgresql.Driver
server:
  port: ${PORT:5000}