spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/persons
    password: test
    username: program
    driver-class-name: org.postgresql.Driver
